name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16    
    - run: npm ci

    - name: Build production demo
      env:
        NODE_OPTIONS: "--max-old-space-size=5120"
      run: npm run build-demo:prod --if-present

    - name: 'Deploy build files'
      run: gsutil -m rsync -d -c -r dist-demo gs://webatlas-vitessce/benchmarking
      
    - name: 'Set HTTP cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=60" gs://webatlas-vitessce/benchmarking/*.html
    - name: 'Set JS cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webatlas-vitessce/benchmarking/static/js/*.js
    - name: 'Set CSS cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://webatlas-vitessce/benchmarking/static/css/*.css
