name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: 'Deploy build files'
      run: gsutil -m rsync -d -c -r build gs://vitessce-benchmarking
      
    - name: 'Set HTTP cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://vitessce-benchmarking/**/*.html
    - name: 'Set JS cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://vitessce-benchmarking/static/js/*.js
    - name: 'Set CSS cache'
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=31536000" gs://vitessce-benchmarking/static/css/*.css
